apiVersion: apps/v1
kind: Deployment
metadata:
  name: cetahyme-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: cgohitema/backend-app:v2
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: cetahyme-mysql-service
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: azerty123
        - name: MYSQL_DATABASE
          value: cgo_database
