apiVersion: apps/v1
kind: Deployment
metadata:
  name: cetahyme-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cgo_backend
  template:
    metadata:
      labels:
        app: cgo_backend
    spec:
      containers:
      - name: cgo_backend-container
        image: cgohitema/backend-app:v3
        ports:
        - containerPort: 5001

