apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgo-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cgo-flask
  template:
    metadata:
      labels:
        app: cgo-flask
    spec:
      containers:
      - name: cgo-flask-container
        image: cgohitema/cgo-backend
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cgo-flask-service
spec:
  selector:
    app: cgo-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
