apiVersion: apps/v1
kind: Deployment
metadata:
  name: cetahyme-back-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cgo-tahyme
  template:
    metadata:
      labels:
        app: cgo-tahyme
    spec:
      containers:
      - name: cgo-tahyme-back-container
        image: cgohitema/backend-app:v4
        ports:
        - containerPort: 5000
