apiVersion: apps/v1
kind: Deployment
metadata:
  name: cetahyme-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: cgohitema/backend-app:v2
        ports:
        - containerPort: 5000
