apiVersion: apps/v1
kind: Deployment
metadata:
  name: CETahyme-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: cgohitema/frontend-app:v5
        ports:
        - containerPort: 80
