name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      #PARTIE AZURE
      - name: Connect to Azure
        run: |
          az login --use-device-code
      - name: Connect to Kubernetes cluster
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group hitema_kube --name hitema --overwrite-existing

      #PARTIE DOCKER
      - name: Build Docker image backend
        run: |
          docker build -t cgohitema/backend-app .
          docker login -u cgohitema -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag  cgohitema/backend-app  cgohitema/backend-app:v2
          docker push  cgohitema/backend-app:v2

      - name: Build Docker image  frontend
        run: |
           cd templates
           docker build -t cgohitema/frontend-app .
           docker login -u cgohitema -p ${{ secrets.DOCKER_PASSWORD }}
           docker tag cgohitema/frontend-app cgohitema/frontend-app:v5
           docker push cgohitema/frontend-app:v1

  
      #PARTIE KUBERNETES
      - name: Apply Kubernetes files
        run: |
          kubectl apply -f mysql-deployment.yaml
          kubectl apply -f mysql-service.yaml
          kubectl apply -f mysql-init-script.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f mysql-pvc.yaml
          kubectl apply -f mysql-pv.yaml
          kubectl apply -f frontend-deployment.yaml
          kubectl apply -f frontend-service.yaml