name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect to Azure
        run: |
          az login --use-device-code
      - name: Connect to Kubernetes cluster
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group hitema_kube --name hitema --overwrite-existing

      - name: Build Docker image
        run: |
          docker build -t cgohitema/backend-app .
          docker login -u cgohitema -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag  cgohitema/backend-app  cgohitema/backend-app:v2
          docker push  cgohitema/backend-app:v2

      - name: Apply Kubernetes files
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml