name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect to Azure
        run: |
          az login ${{ secrets.AZURE_CREDENTIALS }}
      - name: Connect to Kubernetes cluster
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group hitema_kube --name hitema --overwrite-existing

      
      - name: Build Docker image backend
        run: |
          docker build -t cgohitema/backend-app .
          docker login -u cgohitema -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag  cgohitema/backend-app  cgohitema/backend-app:v2
          docker push  cgohitema/backend-app:v2

      - name: Build Docker image  frontend
        run: |
           cd templates
           docker build -t cgohitema/frontend-app .
           docker login -u cgohitema -p ${{ secrets.DOCKER_PASSWORD }}
           docker tag cgohitema/frontend-app cgohitema/frontend-app:v1
           docker push cgohitema/frontend-app:v1
      - name: delete Kubernetes files
        run: |
                kubectl delete -f mysql-deployment.yaml
                kubectl delete -f mysql-service.yaml
                kubectl delete -f deployment.yaml
                kubectl delete -f service.yaml
                kubectl delete -f mysql-pvc.yaml
                kubectl delete -f mysql-pv.yaml
                kubectl delete -f frontend-deployment.yaml
                kubectl delete -f frontend-service.yaml

      - name: Apply Kubernetes files
        run: |
             kubectl apply -f mysql-deployment.yaml
             kubectl apply -f mysql-service.yaml
             kubectl apply -f deployment.yaml
             kubectl apply -f service.yaml
             kubectl apply -f mysql-pvc.yaml
             kubectl apply -f mysql-pv.yaml
             kubectl apply -f frontend-deployment.yaml
             kubectl apply -f frontend-service.yaml