name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login and AKS Set Context
        run: |
          az login --service-principal -u ${{ secrets.appID }} -p ${{ secrets.secret }} --tenant ${{ secrets.tenantID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group hitema_kube --name hitema --overwrite-existing

      - name: Build Docker image
        run: |
          docker build -t  ${{ secrets.DOCKER_USERNAME }}/backend-app .
          docker login -u  ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag  ${{ secrets.DOCKER_USERNAME }}/backend-app  ${{ secrets.DOCKER_USERNAME }}/backend-app:v2
          docker push  ${{ secrets.DOCKER_USERNAME }}/backend-app:v2

      - name: Apply Kubernetes files
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml